import type { Metadata } from "next";
import { Bricolage_Grotesque, Comfortaa } from "next/font/google";
import "./globals.css";
import { CardProvider } from "@/context/CardContext";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "InstaCard",
  description: "Generated by kafa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolageGrotesque.variable} ${comfortaa.variable}  antialiased`}
      >
        <div className="font-comfortaa text-brand-black">
          <CardProvider>{children}</CardProvider>
        </div>
      </body>
    </html>
  );
}
